### ISSUE TITLE
Make release instead of tag

### ISSUE THREAD

**Issue by theChaosCoder** [dubhater/vapoursynth-nrdb#1]
Could you make a "real" release. Currently the github api returns an empty list

[https://api.github.com/repos/dubhater/vapoursynth-nrdb/releases](https://api.github.com/repos/dubhater/vapoursynth-nrdb/releases)

[https://api.github.com/repos/dubhater/vapoursynth-nrdb/tags](https://api.github.com/repos/dubhater/vapoursynth-nrdb/tags)

**Comment by dubhater** [comment]
Okay.

**Comment by theChaosCoder** [comment]
thx
